graph LR
    subgraph Router
        r[Router]
    end

    subgraph Firewall
        f[Firewall]
    end

    subgraph Switch
        sw[Switch]
    end
    
    subgraph CopyCenter
        cc(Copy Center)
    end

    subgraph AccountingOffice
        ao1(Employee 1)
        ao2(Employee 2)
        ao3(Employee 3)
        ao4(Employee 4)
    end

    subgraph TechOffice
        to1(Employee 5)
        to2(Employee 6)
        to3(Employee 7)
        to4(Employee 8)
        to5(Employee 9)
        to6(Employee 10)
    end

    r --> f
    f --> sw
    sw --> cc
    sw --> ao1
    sw --> ao2
    sw --> ao3
    sw --> ao4
    sw --> to1
    sw --> to2
    sw --> to3
    sw --> to4
    sw --> to5
    sw --> to6

