graph LR
    subgraph Router
        r[Router]
    end

    subgraph Firewall
        f[Firewall]
    end

    subgraph Switch
        sw[Switch]
    end
    
    subgraph CopyCenter
        cc(Copy Center)
        sap(Security Access Point)
    end

    subgraph AccountingOffice
        ao1(Employee 1)
        ao2(Employee 2)
        ao3(Employee 3)
        ao4(Employee 4)
    end

    subgraph TechOffice
        to1(Employee 5)
        to2(Employee 6)
        to3(Employee 7)
        to4(Employee 8)
        to5(Employee 9)
        to6(Employee 10)
    end

    r --> f
    f --> sw
    sw --> cc
    sw --> sap
    sap --> ao1
    sap --> ao2
    sap --> ao3
    sap --> ao4
    sap --> to1
    sap --> to2
    sap --> to3
    sap --> to4
    sap --> to5
    sap --> to6
